### ISSUE TITLE
Partner with the developers from MonaServer

### ISSUE THREAD

**Issue by al-sabr** [zenomt/rtmfp-cpp#1]
Hi I was only proposing this idea to communicate with the folks at https://github.com/MonaSolutions/librtmfp

They did most of the major work maybe this could save you some time.

Best Regards

**Comment by zenomt** [comment]
hi @al-sabr. thank you. i am aware of MonaServer and i have communicated with its authors. i decided to write a new implementation of RTMFP because no existing open source implementations i found (including MonaServer's) are correct, complete, or general enough to fully embody the philosophy of RTMFP as its creators\* intended.

\* note that i am a co-creator of RTMFP and the author of its public specifications ([RFC 7016](https://tools.ietf.org/html/rfc7016) and [RFC 7425](https://tools.ietf.org/html/rfc7425)).

**Comment by al-sabr** [comment]
It is an honor to be able to Exchange with you. This Protokoll is really awesome and I think nothing could even beat it. Was so useful in my Projects.

Good to know that it is in good hands.

**Comment by al-sabr** [comment]
I was looking for either librtmfp but now I will use this in this new Projekt

**Comment by zenomt** [comment]
if you have questions, please use [discussions](https://github.com/zenomt/rtmfp-cpp/discussions). i check regularly and am happy to help if i can, especially to clarify documentation or APIs.

please bear in mind that this library and its APIs are lower-level compared to other implementations you might be familiar with (like MonaServer's). this library is at the level of Flows. you can build higher-level constructs like NetConnections, NetStreams, P2P introduction, and load balancers on top of flows and other facilities provided by this library (like `onUnmatchedIHello`, `sendResponderRedirect`, and `forwardIHello`), as described in [RFC 7425](https://tools.ietf.org/html/rfc7425), but the higher-level abstractions aren't currently provided for you. bear in mind too that this library will never directly provide implementations of any functionality not publicly documented by Adobe (for example, anything related to NetGroups, Multicast, or RTMFP Groups), though it's entirely possible to implement all of that on top of the low-level functionality provided by this library.
