### ISSUE TITLE
Discussion are not working creating an issue for Windows port here.

### ISSUE THREAD

**Issue by al-sabr** [zenomt/rtmfp-cpp#11]
Greetings !

I started a Windows port but came to a roadblock because I have no experience with Socket porting from Unix to Windows but somehow I found the bits an pieces from around the web and added new files and modified CMakeLists.txt file to take into consideration WIN32 with vcpkg for Visual Studio 2019 project generation.

I hope that it is going to lead somewhere.

https://github.com/al-sabr/rtmfp-cpp/tree/win32-port

Best Regards

**Comment by zenomt** [comment]
hi @al-sabr . i'm not sure why Discussions isn't working. are you sure you were logged in? i looked with a different account and i had the option to "create a new discussion" (in case it was limited to only the repo owner/me).

regarding Windows: i don't have access to a Windows system and so i would be uncomfortable adding Windows-specific code (especially since i wouldn't be able to tell if i broke something).

i would be willing to add some "if/if-not WIN32" to the CMakeLists.txt file to exclude some source files from building on Windows. but i would prefer Windows-specific additions to be in a separate repo. i'd be happy to link to such a repo in the README.

i'm not a CMake guru, but i believe you could make your Windows CMakeLists.txt reference the main RTMFP repo by location/commit-id as a dependency, and it would get pulled in. then your Windows-specific one would be the top-level CMakeLists.txt for building a Windows library.
