### ISSUE TITLE
Memory Leak Happens if constructor fails

### ISSUE THREAD

**Issue by kartiksain** [zenomt/rtmfp-cpp#24]
https://github.com/zenomt/rtmfp-cpp/blob/d0ee847c880aa37a7a4a900ec4cea55a646cf621/src/RTMFP.cpp#L34

**Comment by zenomt** [comment]
is this a theoretical concern, or one that's causing an actual problem? that is, are you actually experiencing an RTMFP's constructor failing (from, like, out of memory or something), and you're catching the exception and trying to recover without just stopping the process (when you're already super close to out-of-memory)?

i will fix these malloc leaks, but in this same constructor a new reference/retain is made on a shared_ptr that won't be released because the RTMFP destructor won't be called. there's probably lots of other places in the code where dynamic allocation or additional refcounts happen in constructors, that would be leaked if the constructor ultimately failed.

knowing how much of a real problem these kinds of potential leaks are in the real world will help me to prioritize an audit to find them and decide what to do about them.

**Comment by zenomt** [comment]
https://github.com/zenomt/rtmfp-cpp/commit/4f07df76a6e6273c9c111a7173da3f090959dd80 addresses the specific leak you called out. however, without any indication that this kind of leak is causing a real-world problem for anyone, or in fact that anyone actually attempts to catch any exceptions rather than letting the program terminate on exception, i'm not inclined at this time to track down and address others like it.

**Comment by kartiksain** [comment]
Hi Michael,

Thanks for addressing the memory leak in commit 4f07df7.

While I haven’t encountered issues with the RTMFP constructor failing, my concern is more preventive. In environments where multiple programs run together, even small memory leaks—whether from our process or others—can accumulate, potentially leading to failures. Over time, repeated loading and unloading of the library could also contribute to memory leaks.

I am in learning phase and trying to seek some changes for myself with your guidance can enrich me in future.

Best,
Kartik

**Comment by zenomt** [comment]
keep in mind that the kind of situation that could cause this constructor (or any of the other constructors in the library) to fail is that the process is already out of memory. if that's the case, it's probably not possible to continue running anyway (especially in C++ where dynamic allocation happens all over the place). plus, unless you're explicitly catching exceptions, the program will terminate when any constructor fails. being almost or entirely out of allocatable memory in the process is probably going to be unrecoverable, and the [best course of action will be to terminate](https://www.usenix.org/legacy/events/hotos03/tech/full_papers/candea/candea.pdf).
